name: Build my profile description with Node.js
permissions:
  contents: write
on:
  push:
    branches: [ "main" ]
#  schedule:
#    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build templates with Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: "22.x"
        cache: 'npm'
    - run: npm ci
    - run: node index.js
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -f *.md assets/*
        git commit -m "Profile rebuild at $(date '+%Y-%m-%d %H:%m')"
        git push
